// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as client$0 from "../client/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as launcheripc$0 from "../launcheripc/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.SavedCredentials | null>}
 */
export function CheckSavedCredentials() {
    return $Call.ByID(130989340).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckVersion 检查版本更新
 * @returns {$CancellablePromise<$models.VersionCheckResult | null>}
 */
export function CheckVersion() {
    return $Call.ByID(3213254289).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearCredentials() {
    return $Call.ByID(1630845404);
}

/**
 * CloseLoginWindow 关闭登录窗口
 * @returns {$CancellablePromise<void>}
 */
export function CloseLoginWindow() {
    return $Call.ByID(4198148980);
}

/**
 * @param {string} operationID
 * @returns {$CancellablePromise<void>}
 */
export function ConfirmIPCUpdate(operationID) {
    return $Call.ByID(2394152566, operationID);
}

/**
 * ConnectService 快速连接服务
 * @param {string} serviceID
 * @returns {$CancellablePromise<string>}
 */
export function ConnectService(serviceID) {
    return $Call.ByID(2226051968, serviceID);
}

/**
 * CreateLoginSession 通过 gRPC 创建登录会话
 * 返回 session_id 和 login_url（相对路径），前端拼接 server 地址后打开 WebView
 * @param {string} serverAddr
 * @param {string} usernameHint
 * @returns {$CancellablePromise<$models.CreateLoginSessionResult | null>}
 */
export function CreateLoginSession(serverAddr, usernameHint) {
    return $Call.ByID(3992960678, serverAddr, usernameHint).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DeleteDevice 删除设备
 * @param {string} deviceToken
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDevice(deviceToken) {
    return $Call.ByID(1811512340, deviceToken);
}

/**
 * GenerateKubeconfig 自动生成 kubeconfig，为每个已授权的 K8S API 资源创建集群条目
 * 流程：获取 k8sapi 资源 → 触发 DNS 解析（分配 VIP + 启动代理）→ 生成 kubeconfig
 * @returns {$CancellablePromise<$models.KubeconfigResult | null>}
 */
export function GenerateKubeconfig() {
    return $Call.ByID(351207437).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(3210756173).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetDevices 获取设备列表
 * @returns {$CancellablePromise<($models.DeviceInfo | null)[]>}
 */
export function GetDevices() {
    return $Call.ByID(237845170).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetDomainList 获取域名列表
 * @returns {$CancellablePromise<($models.DomainItem | null)[]>}
 */
export function GetDomainList() {
    return $Call.ByID(4215633643).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetGRPCStatus 获取 gRPC 连接状态
 * @returns {$CancellablePromise<$models.GRPCStatus | null>}
 */
export function GetGRPCStatus() {
    return $Call.ByID(3652517293).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetHostServices 获取指定主机的服务列表
 * @param {string} hostID
 * @returns {$CancellablePromise<($models.ServiceInfo | null)[]>}
 */
export function GetHostServices(hostID) {
    return $Call.ByID(3432160785, hostID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetHosts 获取已授权主机列表
 * @returns {$CancellablePromise<($models.HostInfo | null)[]>}
 */
export function GetHosts() {
    return $Call.ByID(2353309006).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * @returns {$CancellablePromise<any>}
 */
export function GetIPCUpdateState() {
    return $Call.ByID(287437795);
}

/**
 * GetLogLevel 获取当前日志级别
 * @returns {$CancellablePromise<string>}
 */
export function GetLogLevel() {
    return $Call.ByID(1453883471);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLogs() {
    return $Call.ByID(1466252692).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * GetProxyStatus 获取所有本地代理连接状态
 * @returns {$CancellablePromise<($models.ProxyStatusInfo | null)[]>}
 */
export function GetProxyStatus() {
    return $Call.ByID(391408139).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * GetResourceTenants returns only Tenant identities represented by the
 * caller's currently authorized v2 resources. It never installs routes.
 * @returns {$CancellablePromise<$models.ResourceTenantInfo[]>}
 */
export function GetResourceTenants() {
    return $Call.ByID(223320176).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * GetResources 获取可访问的资源列表（SSH / K8S API / K8S Service）
 * @returns {$CancellablePromise<(client$0.ResourceInfo | null)[]>}
 */
export function GetResources() {
    return $Call.ByID(2898432568).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * @returns {$CancellablePromise<($models.ServiceInfo | null)[]>}
 */
export function GetServices() {
    return $Call.ByID(2641329379).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetTunnelStatus 获取隧道连接状态
 * @returns {$CancellablePromise<$models.TunnelStatus | null>}
 */
export function GetTunnelStatus() {
    return $Call.ByID(3308965971).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.VersionInfo | null>}
 */
export function GetVersion() {
    return $Call.ByID(1667803041).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType36($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetWindowTitle() {
    return $Call.ByID(1084152535);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function HideToTray() {
    return $Call.ByID(1860420756);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsAuthenticated() {
    return $Call.ByID(2682617328);
}

/**
 * Login 使用已保存的凭证自动认证
 * @param {string} serverAddr
 * @param {string} clientName
 * @param {string} clientSecret
 * @param {boolean} rememberMe
 * @returns {$CancellablePromise<void>}
 */
export function Login(serverAddr, clientName, clientSecret, rememberMe) {
    return $Call.ByID(1682939098, serverAddr, clientName, clientSecret, rememberMe);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Logout() {
    return $Call.ByID(315434483);
}

/**
 * OfflineDevice 让设备下线
 * @param {string} deviceToken
 * @returns {$CancellablePromise<void>}
 */
export function OfflineDevice(deviceToken) {
    return $Call.ByID(153774490, deviceToken);
}

/**
 * OpenBrowser 打开浏览器
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenBrowser(url) {
    return $Call.ByID(869870267, url);
}

/**
 * OpenLoginWindow 打开登录窗口（在 Desktop 内部的 WebView 中）
 * 用于 Logto 登录流程
 * @param {string} loginURL
 * @returns {$CancellablePromise<void>}
 */
export function OpenLoginWindow(loginURL) {
    return $Call.ByID(2300745098, loginURL);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(3341140757);
}

/**
 * ReconnectTunnel 重新连接隧道
 * @returns {$CancellablePromise<void>}
 */
export function ReconnectTunnel() {
    return $Call.ByID(409053384);
}

/**
 * @param {launcheripc$0.UpdateRequest | null} req
 * @returns {$CancellablePromise<any>}
 */
export function RequestIPCUpdate(req) {
    return $Call.ByID(180522793, req);
}

/**
 * SetContainerServiceLocalPort changes only this device's listener port. The
 * Kubernetes Service target port remains resource.Port.
 * @param {string} resourceID
 * @param {number} localPort
 * @returns {$CancellablePromise<(client$0.ResourceInfo | null)[]>}
 */
export function SetContainerServiceLocalPort(resourceID, localPort) {
    return $Call.ByID(1340784315, resourceID, localPort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * SetLogLevel 设置日志级别
 * @param {string} level
 * @returns {$CancellablePromise<void>}
 */
export function SetLogLevel(level) {
    return $Call.ByID(3894151323, level);
}

/**
 * SetRuntime attaches the Wails application resources used by window and tray actions.
 * @param {application$0.App | null} mainApp
 * @param {application$0.WebviewWindow | null} mainWindow
 * @param {string} appIcon
 * @returns {$CancellablePromise<void>}
 */
export function SetRuntime(mainApp, mainWindow, appIcon) {
    return $Call.ByID(812954509, mainApp, mainWindow, appIcon);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowFromTray() {
    return $Call.ByID(2320187068);
}

/**
 * Startup initializes the desktop service after the Wails runtime is ready.
 * @returns {$CancellablePromise<void>}
 */
export function Startup() {
    return $Call.ByID(3099736274);
}

/**
 * SwitchResourceTenant changes only the local scope. Resource fetching is an
 * explicit administrator action performed later through GetResources.
 * @param {string} tenantID
 * @returns {$CancellablePromise<(client$0.ResourceInfo | null)[]>}
 */
export function SwitchResourceTenant(tenantID) {
    return $Call.ByID(418404945, tenantID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * ToggleFavorite 切换服务收藏状态
 * @param {string} serviceID
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleFavorite(serviceID) {
    return $Call.ByID(3448283653, serviceID);
}

/**
 * @param {string} serverAddr
 * @param {string} sessionID
 * @param {string} deviceFingerprint
 * @returns {$CancellablePromise<$models.LoginResultGRPC | null>}
 */
export function WaitForLoginResultGRPC(serverAddr, sessionID, deviceFingerprint) {
    return $Call.ByID(3344282757, serverAddr, sessionID, deviceFingerprint).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType38($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SavedCredentials.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.VersionCheckResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.CreateLoginSessionResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.KubeconfigResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = config$0.Config.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.DeviceInfo.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.DomainItem.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.GRPCStatus.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $models.ServiceInfo.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.HostInfo.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = $Create.Array($Create.Any);
const $$createType25 = $models.ProxyStatusInfo.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = $models.ResourceTenantInfo.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = client$0.ResourceInfo.createFrom;
const $$createType31 = $Create.Nullable($$createType30);
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = $models.TunnelStatus.createFrom;
const $$createType34 = $Create.Nullable($$createType33);
const $$createType35 = $models.VersionInfo.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = $models.LoginResultGRPC.createFrom;
const $$createType38 = $Create.Nullable($$createType37);
