// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as launcher$0 from "../launcher/models.js";

/**
 * CreateLoginSessionResult 创建登录会话结果（暴露给前端）
 */
export class CreateLoginSessionResult {
    /**
     * Creates a new CreateLoginSessionResult instance.
     * @param {Partial<CreateLoginSessionResult>} [$$source = {}] - The source object to create the CreateLoginSessionResult.
     */
    constructor($$source = {}) {
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (!("login_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["login_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateLoginSessionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateLoginSessionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateLoginSessionResult(/** @type {Partial<CreateLoginSessionResult>} */($$parsedSource));
    }
}

export class DesktopUpdateState {
    /**
     * Creates a new DesktopUpdateState instance.
     * @param {Partial<DesktopUpdateState>} [$$source = {}] - The source object to create the DesktopUpdateState.
     */
    constructor($$source = {}) {
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (!("current_commit_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_commit_id"] = "";
        }
        if (!("current_commit_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_commit_time"] = "";
        }
        if (!("checked_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checked_at"] = "";
        }
        if (!("manifest" in $$source)) {
            /**
             * @member
             * @type {launcher$0.PublicManifest | null}
             */
            this["manifest"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopUpdateState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DesktopUpdateState}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manifest" in $$parsedSource) {
            $$parsedSource["manifest"] = $$createField4_0($$parsedSource["manifest"]);
        }
        return new DesktopUpdateState(/** @type {Partial<DesktopUpdateState>} */($$parsedSource));
    }
}

/**
 * DeviceInfo 设备信息
 */
export class DeviceInfo {
    /**
     * Creates a new DeviceInfo instance.
     * @param {Partial<DeviceInfo>} [$$source = {}] - The source object to create the DeviceInfo.
     */
    constructor($$source = {}) {
        if (!("device_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["device_token"] = "";
        }
        if (!("device_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["device_name"] = "";
        }
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("last_used_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_used_at"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("is_current" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_current"] = false;
        }
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceInfo(/** @type {Partial<DeviceInfo>} */($$parsedSource));
    }
}

/**
 * DomainItem 域名项（用于前端）
 */
export class DomainItem {
    /**
     * Creates a new DomainItem instance.
     * @param {Partial<DomainItem>} [$$source = {}] - The source object to create the DomainItem.
     */
    constructor($$source = {}) {
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("ssh_users" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ssh_users"] = [];
        }
        if (!("region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["region"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["display_name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["resource_id"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DomainItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DomainItem}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh_users" in $$parsedSource) {
            $$parsedSource["ssh_users"] = $$createField3_0($$parsedSource["ssh_users"]);
        }
        return new DomainItem(/** @type {Partial<DomainItem>} */($$parsedSource));
    }
}

/**
 * GRPCStatus gRPC 连接状态
 */
export class GRPCStatus {
    /**
     * Creates a new GRPCStatus instance.
     * @param {Partial<GRPCStatus>} [$$source = {}] - The source object to create the GRPCStatus.
     */
    constructor($$source = {}) {
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("server_address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_address"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GRPCStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GRPCStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GRPCStatus(/** @type {Partial<GRPCStatus>} */($$parsedSource));
    }
}

/**
 * HostInfo 主机信息
 */
export class HostInfo {
    /**
     * Creates a new HostInfo instance.
     * @param {Partial<HostInfo>} [$$source = {}] - The source object to create the HostInfo.
     */
    constructor($$source = {}) {
        if (!("host_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_id"] = "";
        }
        if (!("host_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_name"] = "";
        }
        if (!("tunnel_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnel_ip"] = "";
        }
        if (!("ssh_users" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ssh_users"] = [];
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("last_seen" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_seen"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh_users" in $$parsedSource) {
            $$parsedSource["ssh_users"] = $$createField3_0($$parsedSource["ssh_users"]);
        }
        return new HostInfo(/** @type {Partial<HostInfo>} */($$parsedSource));
    }
}

export class KubeconfigInstallRequest {
    /**
     * Creates a new KubeconfigInstallRequest instance.
     * @param {Partial<KubeconfigInstallRequest>} [$$source = {}] - The source object to create the KubeconfigInstallRequest.
     */
    constructor($$source = {}) {
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("target_ids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["target_ids"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KubeconfigInstallRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KubeconfigInstallRequest}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("target_ids" in $$parsedSource) {
            $$parsedSource["target_ids"] = $$createField1_0($$parsedSource["target_ids"]);
        }
        return new KubeconfigInstallRequest(/** @type {Partial<KubeconfigInstallRequest>} */($$parsedSource));
    }
}

export class KubeconfigInstallResult {
    /**
     * Creates a new KubeconfigInstallResult instance.
     * @param {Partial<KubeconfigInstallResult>} [$$source = {}] - The source object to create the KubeconfigInstallResult.
     */
    constructor($$source = {}) {
        if (!("context" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["context"] = "";
        }
        if (!("targets" in $$source)) {
            /**
             * @member
             * @type {(KubeconfigTargetResult | null)[]}
             */
            this["targets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KubeconfigInstallResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KubeconfigInstallResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField1_0($$parsedSource["targets"]);
        }
        return new KubeconfigInstallResult(/** @type {Partial<KubeconfigInstallResult>} */($$parsedSource));
    }
}

/**
 * KubeconfigResult kubeconfig 生成结果
 */
export class KubeconfigResult {
    /**
     * Creates a new KubeconfigResult instance.
     * @param {Partial<KubeconfigResult>} [$$source = {}] - The source object to create the KubeconfigResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * kubeconfig 文件路径
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("clusters" in $$source)) {
            /**
             * 已配置的集群名称列表
             * @member
             * @type {string[]}
             */
            this["clusters"] = [];
        }
        if (!("count" in $$source)) {
            /**
             * 集群数量
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KubeconfigResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KubeconfigResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("clusters" in $$parsedSource) {
            $$parsedSource["clusters"] = $$createField1_0($$parsedSource["clusters"]);
        }
        return new KubeconfigResult(/** @type {Partial<KubeconfigResult>} */($$parsedSource));
    }
}

export class KubeconfigTarget {
    /**
     * Creates a new KubeconfigTarget instance.
     * @param {Partial<KubeconfigTarget>} [$$source = {}] - The source object to create the KubeconfigTarget.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("hint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KubeconfigTarget instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KubeconfigTarget}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KubeconfigTarget(/** @type {Partial<KubeconfigTarget>} */($$parsedSource));
    }
}

export class KubeconfigTargetResult {
    /**
     * Creates a new KubeconfigTargetResult instance.
     * @param {Partial<KubeconfigTargetResult>} [$$source = {}] - The source object to create the KubeconfigTargetResult.
     */
    constructor($$source = {}) {
        if (!("target_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target_id"] = "";
        }
        if (!("target_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target_name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("context" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["context"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KubeconfigTargetResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KubeconfigTargetResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KubeconfigTargetResult(/** @type {Partial<KubeconfigTargetResult>} */($$parsedSource));
    }
}

/**
 * WaitForLoginResultGRPC 通过 gRPC 双向流等待登录结果
 * 此方法建立 gRPC 连接，等待 Server 推送登录结果
 * 返回登录成功的凭证信息
 */
export class LoginResultGRPC {
    /**
     * Creates a new LoginResultGRPC instance.
     * @param {Partial<LoginResultGRPC>} [$$source = {}] - The source object to create the LoginResultGRPC.
     */
    constructor($$source = {}) {
        if (!("Success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Success"] = false;
        }
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Message"] = "";
        }
        if (!("IsDisabled" in $$source)) {
            /**
             * 用户已禁用/待审批
             * @member
             * @type {boolean}
             */
            this["IsDisabled"] = false;
        }
        if (!("DesktopID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DesktopID"] = 0;
        }
        if (!("DeviceToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DeviceToken"] = "";
        }
        if (!("AuthKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AuthKey"] = "";
        }
        if (!("ServerURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ServerURL"] = "";
        }
        if (!("Username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginResultGRPC instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoginResultGRPC}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoginResultGRPC(/** @type {Partial<LoginResultGRPC>} */($$parsedSource));
    }
}

/**
 * ProxyStatusInfo 代理连接状态信息
 */
export class ProxyStatusInfo {
    /**
     * Creates a new ProxyStatusInfo instance.
     * @param {Partial<ProxyStatusInfo>} [$$source = {}] - The source object to create the ProxyStatusInfo.
     */
    constructor($$source = {}) {
        if (!("domain" in $$source)) {
            /**
             * 域名
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("vip" in $$source)) {
            /**
             * 本地 VIP 地址
             * @member
             * @type {string}
             */
            this["vip"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * 监听端口
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("remote_addr" in $$source)) {
            /**
             * 远程地址
             * @member
             * @type {string}
             */
            this["remote_addr"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * 类型：tcp / svc
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("tls" in $$source)) {
            /**
             * 是否 TLS
             * @member
             * @type {boolean}
             */
            this["tls"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyStatusInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyStatusInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyStatusInfo(/** @type {Partial<ProxyStatusInfo>} */($$parsedSource));
    }
}

export class ResourceTenantInfo {
    /**
     * Creates a new ResourceTenantInfo instance.
     * @param {Partial<ResourceTenantInfo>} [$$source = {}] - The source object to create the ResourceTenantInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceTenantInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResourceTenantInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceTenantInfo(/** @type {Partial<ResourceTenantInfo>} */($$parsedSource));
    }
}

export class SavedCredentials {
    /**
     * Creates a new SavedCredentials instance.
     * @param {Partial<SavedCredentials>} [$$source = {}] - The source object to create the SavedCredentials.
     */
    constructor($$source = {}) {
        if (!("server_address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_address"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("client_secret" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_secret"] = "";
        }
        if (!("remember_me" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["remember_me"] = false;
        }
        if (!("has_token" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_token"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedCredentials instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SavedCredentials}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedCredentials(/** @type {Partial<SavedCredentials>} */($$parsedSource));
    }
}

/**
 * ServiceInfo 服务信息（用于前端显示）
 */
export class ServiceInfo {
    /**
     * Creates a new ServiceInfo instance.
     * @param {Partial<ServiceInfo>} [$$source = {}] - The source object to create the ServiceInfo.
     */
    constructor($$source = {}) {
        if (!("instance_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["instance_id"] = 0;
        }
        if (!("instance_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["instance_name"] = "";
        }
        if (!("agent_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent_name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("service_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["service_port"] = 0;
        }
        if (!("service_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["service_ip"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["preferred_port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (!("is_favorite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_favorite"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["agent_tailscale_ip"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["listen_port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["target_addr"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 服务唯一标识
             * @member
             * @type {string | undefined}
             */
            this["service_id"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServiceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceInfo(/** @type {Partial<ServiceInfo>} */($$parsedSource));
    }
}

/**
 * TunnelStatus 隧道状态信息
 */
export class TunnelStatus {
    /**
     * Creates a new TunnelStatus instance.
     * @param {Partial<TunnelStatus>} [$$source = {}] - The source object to create the TunnelStatus.
     */
    constructor($$source = {}) {
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelStatus(/** @type {Partial<TunnelStatus>} */($$parsedSource));
    }
}

/**
 * VersionCheckResult 版本检查结果
 */
export class VersionCheckResult {
    /**
     * Creates a new VersionCheckResult instance.
     * @param {Partial<VersionCheckResult>} [$$source = {}] - The source object to create the VersionCheckResult.
     */
    constructor($$source = {}) {
        if (!("has_update" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_update"] = false;
        }
        if (!("latest_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latest_version"] = "";
        }
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (!("update_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["update_url"] = "";
        }
        if (!("release_notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionCheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionCheckResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionCheckResult(/** @type {Partial<VersionCheckResult>} */($$parsedSource));
    }
}

export class VersionInfo {
    /**
     * Creates a new VersionInfo instance.
     * @param {Partial<VersionInfo>} [$$source = {}] - The source object to create the VersionInfo.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("gitCommit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gitCommit"] = "";
        }
        if (!("commitTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commitTime"] = "";
        }
        if (!("buildNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildNumber"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionInfo(/** @type {Partial<VersionInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = launcher$0.PublicManifest.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = KubeconfigTargetResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
