// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ServiceInfo 表示一个可访问的服务
 */
export class ServiceInfo {
    /**
     * Creates a new ServiceInfo instance.
     * @param {Partial<ServiceInfo>} [$$source = {}] - The source object to create the ServiceInfo.
     */
    constructor($$source = {}) {
        if (!("instance_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["instance_id"] = 0;
        }
        if (!("instance_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["instance_name"] = "";
        }
        if (!("agent_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent_name"] = "";
        }
        if (!("service_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["service_type"] = "";
        }
        if (!("service_port" in $$source)) {
            /**
             * Agent端的本地服务端口
             * @member
             * @type {number}
             */
            this["service_port"] = 0;
        }
        if (!("service_ip" in $$source)) {
            /**
             * Agent端的本地服务IP
             * @member
             * @type {string}
             */
            this["service_ip"] = "";
        }
        if (!("preferred_port" in $$source)) {
            /**
             * 用户偏好的本地端口
             * @member
             * @type {number}
             */
            this["preferred_port"] = 0;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("secret_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["secret_key"] = "";
        }
        if (!("access_type" in $$source)) {
            /**
             * 'public', 'private', 'group'
             * @member
             * @type {string}
             */
            this["access_type"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * 'online', 'offline'
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("is_favorite" in $$source)) {
            /**
             * 是否收藏
             * @member
             * @type {boolean}
             */
            this["is_favorite"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServiceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceInfo(/** @type {Partial<ServiceInfo>} */($$parsedSource));
    }
}
