// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as client$0 from "./internal/client/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckSavedCredentials 检查是否有保存的凭据
 * @returns {$CancellablePromise<$models.SavedCredentials | null>}
 */
export function CheckSavedCredentials() {
    return $Call.ByID(1107707788).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckVersion 检查客户端版本
 * @param {string} serverAddr
 * @returns {$CancellablePromise<client$0.VersionCheckResponse | null>}
 */
export function CheckVersion(serverAddr) {
    return $Call.ByID(3248805153, serverAddr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ClearCredentials 清除保存的凭据
 * @returns {$CancellablePromise<void>}
 */
export function ClearCredentials() {
    return $Call.ByID(4195903180);
}

/**
 * ConnectService 连接服务
 * @param {number} instanceID
 * @param {number} localPort
 * @returns {$CancellablePromise<void>}
 */
export function ConnectService(instanceID, localPort) {
    return $Call.ByID(1728507696, instanceID, localPort);
}

/**
 * DeleteDevice 删除设备记录
 * @param {string} deviceToken
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDevice(deviceToken) {
    return $Call.ByID(2539306500, deviceToken);
}

/**
 * DisconnectService 断开服务
 * @param {number} instanceID
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectService(instanceID) {
    return $Call.ByID(1422720182, instanceID);
}

/**
 * GetConfig 获取配置
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetDevices 获取已登录的设备列表
 * @returns {$CancellablePromise<($models.DeviceInfo | null)[]>}
 */
export function GetDevices() {
    return $Call.ByID(2647233474).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetLogs 获取日志（最近 100 行）
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLogs() {
    return $Call.ByID(1743981476).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetServices 获取服务列表
 * @returns {$CancellablePromise<(models$0.ServiceInfo | null)[]>}
 */
export function GetServices() {
    return $Call.ByID(839930963).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetVersion 获取版本信息
 * @returns {$CancellablePromise<$models.VersionInfo | null>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetWindowTitle 获取窗口标题
 * @returns {$CancellablePromise<string>}
 */
export function GetWindowTitle() {
    return $Call.ByID(2749040295);
}

/**
 * HideToTray 隐藏窗口到系统托盘
 * @returns {$CancellablePromise<void>}
 */
export function HideToTray() {
    return $Call.ByID(2285725636);
}

/**
 * IsAuthenticated 检查是否已认证
 * @returns {$CancellablePromise<boolean>}
 */
export function IsAuthenticated() {
    return $Call.ByID(3283000736);
}

/**
 * Login 用户登录
 * @param {string} serverAddr
 * @param {string} clientID
 * @param {string} clientSecret
 * @param {boolean} rememberMe
 * @returns {$CancellablePromise<void>}
 */
export function Login(serverAddr, clientID, clientSecret, rememberMe) {
    return $Call.ByID(1387155178, serverAddr, clientID, clientSecret, rememberMe);
}

/**
 * Logout 用户登出
 * @returns {$CancellablePromise<void>}
 */
export function Logout() {
    return $Call.ByID(1110373539);
}

/**
 * OfflineDevice 让设备下线
 * @param {string} deviceToken
 * @returns {$CancellablePromise<void>}
 */
export function OfflineDevice(deviceToken) {
    return $Call.ByID(693636298, deviceToken);
}

/**
 * QuitApp 完全退出应用
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(3730234565);
}

/**
 * ShowFromTray 从系统托盘恢复窗口
 * @returns {$CancellablePromise<void>}
 */
export function ShowFromTray() {
    return $Call.ByID(140041132);
}

/**
 * ToggleFavorite 切换服务收藏状态（带端口）
 * @param {number} instanceID
 * @param {number} localPort
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleFavorite(instanceID, localPort) {
    return $Call.ByID(1319626997, instanceID, localPort);
}

/**
 * UpdateFavoritePort 更新收藏服务的端口
 * @param {number} instanceID
 * @param {number} localPort
 * @returns {$CancellablePromise<void>}
 */
export function UpdateFavoritePort(instanceID, localPort) {
    return $Call.ByID(528842443, instanceID, localPort);
}

// Private type creation functions
const $$createType0 = $models.SavedCredentials.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = client$0.VersionCheckResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = config$0.Config.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.DeviceInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = models$0.ServiceInfo.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.VersionInfo.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
