// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.SavedCredentials | null>}
 */
export function CheckSavedCredentials() {
    return $Call.ByID(1107707788).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckVersion 检查版本更新
 * @returns {$CancellablePromise<$models.VersionCheckResult | null>}
 */
export function CheckVersion() {
    return $Call.ByID(3248805153).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearCredentials() {
    return $Call.ByID(4195903180);
}

/**
 * DeleteDevice 删除设备
 * @param {string} deviceToken
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDevice(deviceToken) {
    return $Call.ByID(2539306500, deviceToken);
}

/**
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetDevices 获取设备列表
 * @returns {$CancellablePromise<($models.DeviceInfo | null)[]>}
 */
export function GetDevices() {
    return $Call.ByID(2647233474).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetLogLevel 获取当前日志级别
 * @returns {$CancellablePromise<string>}
 */
export function GetLogLevel() {
    return $Call.ByID(2884930143);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLogs() {
    return $Call.ByID(1743981476).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<($models.ServiceInfo | null)[]>}
 */
export function GetServices() {
    return $Call.ByID(839930963).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetTunnelStatus 获取隧道连接状态
 * @returns {$CancellablePromise<$models.TunnelStatus | null>}
 */
export function GetTunnelStatus() {
    return $Call.ByID(1614806691).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.VersionInfo | null>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetWindowTitle() {
    return $Call.ByID(2749040295);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function HideToTray() {
    return $Call.ByID(2285725636);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsAuthenticated() {
    return $Call.ByID(3283000736);
}

/**
 * Login 登录（首次登录或密码登录）
 * @param {string} serverAddr
 * @param {string} clientName
 * @param {string} clientSecret
 * @param {boolean} rememberMe
 * @returns {$CancellablePromise<void>}
 */
export function Login(serverAddr, clientName, clientSecret, rememberMe) {
    return $Call.ByID(1387155178, serverAddr, clientName, clientSecret, rememberMe);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Logout() {
    return $Call.ByID(1110373539);
}

/**
 * OfflineDevice 让设备下线
 * @param {string} deviceToken
 * @returns {$CancellablePromise<void>}
 */
export function OfflineDevice(deviceToken) {
    return $Call.ByID(693636298, deviceToken);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(3730234565);
}

/**
 * ReconnectTunnel 重新连接隧道
 * @returns {$CancellablePromise<void>}
 */
export function ReconnectTunnel() {
    return $Call.ByID(3980011288);
}

/**
 * SetLogLevel 设置日志级别
 * @param {string} level
 * @returns {$CancellablePromise<void>}
 */
export function SetLogLevel(level) {
    return $Call.ByID(2079598923, level);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowFromTray() {
    return $Call.ByID(140041132);
}

/**
 * ToggleFavorite 切换服务收藏状态
 * @param {number} instanceID
 * @param {number} desktopID
 * @returns {$CancellablePromise<void>}
 */
export function ToggleFavorite(instanceID, desktopID) {
    return $Call.ByID(1319626997, instanceID, desktopID);
}

// Private type creation functions
const $$createType0 = $models.SavedCredentials.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.VersionCheckResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = config$0.Config.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.DeviceInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = $models.ServiceInfo.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.TunnelStatus.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $models.VersionInfo.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
