// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DeviceInfo 设备信息
 */
export class DeviceInfo {
    /**
     * Creates a new DeviceInfo instance.
     * @param {Partial<DeviceInfo>} [$$source = {}] - The source object to create the DeviceInfo.
     */
    constructor($$source = {}) {
        if (!("device_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["device_token"] = "";
        }
        if (!("device_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["device_name"] = "";
        }
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("last_used_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_used_at"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("is_current" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_current"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceInfo(/** @type {Partial<DeviceInfo>} */($$parsedSource));
    }
}

/**
 * SavedCredentials 保存的凭据
 */
export class SavedCredentials {
    /**
     * Creates a new SavedCredentials instance.
     * @param {Partial<SavedCredentials>} [$$source = {}] - The source object to create the SavedCredentials.
     */
    constructor($$source = {}) {
        if (!("server_address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_address"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("client_secret" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_secret"] = "";
        }
        if (!("remember_me" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["remember_me"] = false;
        }
        if (!("has_token" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_token"] = false;
        }
        if (!("is_online" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_online"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedCredentials instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SavedCredentials}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedCredentials(/** @type {Partial<SavedCredentials>} */($$parsedSource));
    }
}

/**
 * VersionInfo 版本信息结构
 */
export class VersionInfo {
    /**
     * Creates a new VersionInfo instance.
     * @param {Partial<VersionInfo>} [$$source = {}] - The source object to create the VersionInfo.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("gitCommit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gitCommit"] = "";
        }
        if (!("buildDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildDate"] = "";
        }
        if (!("buildNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildNumber"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionInfo(/** @type {Partial<VersionInfo>} */($$parsedSource));
    }
}
