// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DeviceInfo 设备信息
 */
export class DeviceInfo {
    /**
     * Creates a new DeviceInfo instance.
     * @param {Partial<DeviceInfo>} [$$source = {}] - The source object to create the DeviceInfo.
     */
    constructor($$source = {}) {
        if (!("device_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["device_token"] = "";
        }
        if (!("device_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["device_name"] = "";
        }
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("last_used_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_used_at"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("is_current" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_current"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceInfo(/** @type {Partial<DeviceInfo>} */($$parsedSource));
    }
}

/**
 * GRPCStatus gRPC 连接状态
 */
export class GRPCStatus {
    /**
     * Creates a new GRPCStatus instance.
     * @param {Partial<GRPCStatus>} [$$source = {}] - The source object to create the GRPCStatus.
     */
    constructor($$source = {}) {
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("server_address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_address"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GRPCStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GRPCStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GRPCStatus(/** @type {Partial<GRPCStatus>} */($$parsedSource));
    }
}

/**
 * HostInfo 主机信息
 */
export class HostInfo {
    /**
     * Creates a new HostInfo instance.
     * @param {Partial<HostInfo>} [$$source = {}] - The source object to create the HostInfo.
     */
    constructor($$source = {}) {
        if (!("host_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_id"] = "";
        }
        if (!("host_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_name"] = "";
        }
        if (!("tunnel_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnel_ip"] = "";
        }
        if (!("ssh_users" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ssh_users"] = [];
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("last_seen" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_seen"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh_users" in $$parsedSource) {
            $$parsedSource["ssh_users"] = $$createField3_0($$parsedSource["ssh_users"]);
        }
        return new HostInfo(/** @type {Partial<HostInfo>} */($$parsedSource));
    }
}

/**
 * WaitForLoginResultGRPC 通过 gRPC 双向流等待登录结果
 * 此方法建立 gRPC 连接，等待 Server 推送登录结果
 * 返回登录成功的凭证信息
 */
export class LoginResultGRPC {
    /**
     * Creates a new LoginResultGRPC instance.
     * @param {Partial<LoginResultGRPC>} [$$source = {}] - The source object to create the LoginResultGRPC.
     */
    constructor($$source = {}) {
        if (!("Success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Success"] = false;
        }
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Message"] = "";
        }
        if (!("DesktopID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DesktopID"] = 0;
        }
        if (!("DeviceToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DeviceToken"] = "";
        }
        if (!("AuthKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AuthKey"] = "";
        }
        if (!("ServerURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ServerURL"] = "";
        }
        if (!("Username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginResultGRPC instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoginResultGRPC}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoginResultGRPC(/** @type {Partial<LoginResultGRPC>} */($$parsedSource));
    }
}

export class SavedCredentials {
    /**
     * Creates a new SavedCredentials instance.
     * @param {Partial<SavedCredentials>} [$$source = {}] - The source object to create the SavedCredentials.
     */
    constructor($$source = {}) {
        if (!("server_address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_address"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("client_secret" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_secret"] = "";
        }
        if (!("remember_me" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["remember_me"] = false;
        }
        if (!("has_token" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_token"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedCredentials instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SavedCredentials}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedCredentials(/** @type {Partial<SavedCredentials>} */($$parsedSource));
    }
}

/**
 * ServiceInfo 服务信息（用于前端显示）
 */
export class ServiceInfo {
    /**
     * Creates a new ServiceInfo instance.
     * @param {Partial<ServiceInfo>} [$$source = {}] - The source object to create the ServiceInfo.
     */
    constructor($$source = {}) {
        if (!("instance_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["instance_id"] = 0;
        }
        if (!("instance_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["instance_name"] = "";
        }
        if (!("agent_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent_name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("service_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["service_port"] = 0;
        }
        if (!("service_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["service_ip"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["preferred_port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (!("is_favorite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_favorite"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["agent_tailscale_ip"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["listen_port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["target_addr"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 服务唯一标识
             * @member
             * @type {string | undefined}
             */
            this["service_id"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServiceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceInfo(/** @type {Partial<ServiceInfo>} */($$parsedSource));
    }
}

/**
 * TunnelStatus 隧道状态信息
 */
export class TunnelStatus {
    /**
     * Creates a new TunnelStatus instance.
     * @param {Partial<TunnelStatus>} [$$source = {}] - The source object to create the TunnelStatus.
     */
    constructor($$source = {}) {
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelStatus(/** @type {Partial<TunnelStatus>} */($$parsedSource));
    }
}

/**
 * VersionCheckResult 版本检查结果
 */
export class VersionCheckResult {
    /**
     * Creates a new VersionCheckResult instance.
     * @param {Partial<VersionCheckResult>} [$$source = {}] - The source object to create the VersionCheckResult.
     */
    constructor($$source = {}) {
        if (!("has_update" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_update"] = false;
        }
        if (!("latest_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latest_version"] = "";
        }
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (!("update_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["update_url"] = "";
        }
        if (!("release_notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionCheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionCheckResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionCheckResult(/** @type {Partial<VersionCheckResult>} */($$parsedSource));
    }
}

export class VersionInfo {
    /**
     * Creates a new VersionInfo instance.
     * @param {Partial<VersionInfo>} [$$source = {}] - The source object to create the VersionInfo.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("gitCommit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gitCommit"] = "";
        }
        if (!("buildDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildDate"] = "";
        }
        if (!("buildNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildNumber"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionInfo(/** @type {Partial<VersionInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
