// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * VersionCheckResponse 版本检查响应
 */
export class VersionCheckResponse {
    /**
     * Creates a new VersionCheckResponse instance.
     * @param {Partial<VersionCheckResponse>} [$$source = {}] - The source object to create the VersionCheckResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("version_valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["version_valid"] = false;
        }
        if (!("min_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["min_version"] = "";
        }
        if (!("download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_url"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionCheckResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionCheckResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionCheckResponse(/** @type {Partial<VersionCheckResponse>} */($$parsedSource));
    }
}
