// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config 是 Desktop 应用的配置（内存中使用）
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("server_address" in $$source)) {
            /**
             * Server gRPC 地址，例如 "localhost:8081"
             * @member
             * @type {string}
             */
            this["server_address"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * Client ID（用户名/邮箱）
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("client_secret" in $$source)) {
            /**
             * Client Secret（加密存储）
             * @member
             * @type {string}
             */
            this["client_secret"] = "";
        }
        if (!("device_token" in $$source)) {
            /**
             * Device Token（用于自动登录）
             * @member
             * @type {string}
             */
            this["device_token"] = "";
        }
        if (!("remember_me" in $$source)) {
            /**
             * 是否记住登录
             * @member
             * @type {boolean}
             */
            this["remember_me"] = false;
        }
        if (!("token_expires_at" in $$source)) {
            /**
             * Token 过期时间（Unix 时间戳）
             * @member
             * @type {number}
             */
            this["token_expires_at"] = 0;
        }
        if (!("tunnel_token" in $$source)) {
            /**
             * 隧道认证 Token
             * @member
             * @type {string}
             */
            this["tunnel_token"] = "";
        }
        if (!("tunnel_server" in $$source)) {
            /**
             * 隧道服务器地址
             * @member
             * @type {string}
             */
            this["tunnel_server"] = "";
        }
        if (!("tunnel_port" in $$source)) {
            /**
             * 隧道服务器端口
             * @member
             * @type {number}
             */
            this["tunnel_port"] = 0;
        }
        if (!("port_preferences" in $$source)) {
            /**
             * 服务 ID -> 本地端口映射
             * @member
             * @type {{ [_: `${number}`]: number }}
             */
            this["port_preferences"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("port_preferences" in $$parsedSource) {
            $$parsedSource["port_preferences"] = $$createField9_0($$parsedSource["port_preferences"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
