// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSavedCredentials() {
  return window['go']['main']['App']['CheckSavedCredentials']();
}

export function ClearCredentials() {
  return window['go']['main']['App']['ClearCredentials']();
}

export function ConnectService(arg1, arg2) {
  return window['go']['main']['App']['ConnectService'](arg1, arg2);
}

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function DisconnectService(arg1) {
  return window['go']['main']['App']['DisconnectService'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWindowTitle() {
  return window['go']['main']['App']['GetWindowTitle']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function Login(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3, arg4);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OfflineDevice(arg1) {
  return window['go']['main']['App']['OfflineDevice'](arg1);
}
