// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectService(arg1, arg2) {
  return window['go']['main']['App']['ConnectService'](arg1, arg2);
}

export function DisconnectService(arg1) {
  return window['go']['main']['App']['DisconnectService'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}
