// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {client} from '../models';
import {config} from '../models';
import {models} from '../models';

export function CheckSavedCredentials():Promise<main.SavedCredentials>;

export function CheckVersion(arg1:string):Promise<client.VersionCheckResponse>;

export function ClearCredentials():Promise<void>;

export function ConnectService(arg1:number,arg2:number):Promise<void>;

export function DeleteDevice(arg1:string):Promise<void>;

export function DisconnectService(arg1:number):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetDevices():Promise<Array<main.DeviceInfo>>;

export function GetLogs():Promise<Array<string>>;

export function GetServices():Promise<Array<models.ServiceInfo>>;

export function GetVersion():Promise<main.VersionInfo>;

export function GetWindowTitle():Promise<string>;

export function IsAuthenticated():Promise<boolean>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function Logout():Promise<void>;

export function OfflineDevice(arg1:string):Promise<void>;

export function ToggleFavorite(arg1:number,arg2:number):Promise<boolean>;

export function UpdateFavoritePort(arg1:number,arg2:number):Promise<void>;
