// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as launcheripc$0 from "../launcheripc/models.js";

export class ManifestArtifacts {
    /**
     * Creates a new ManifestArtifacts instance.
     * @param {Partial<ManifestArtifacts>} [$$source = {}] - The source object to create the ManifestArtifacts.
     */
    constructor($$source = {}) {
        if (!("app" in $$source)) {
            /**
             * @member
             * @type {launcheripc$0.ArtifactPayload | null}
             */
            this["app"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManifestArtifacts instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ManifestArtifacts}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("app" in $$parsedSource) {
            $$parsedSource["app"] = $$createField0_0($$parsedSource["app"]);
        }
        return new ManifestArtifacts(/** @type {Partial<ManifestArtifacts>} */($$parsedSource));
    }
}

export class ManifestRelease {
    /**
     * Creates a new ManifestRelease instance.
     * @param {Partial<ManifestRelease>} [$$source = {}] - The source object to create the ManifestRelease.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("commit_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commit_id"] = "";
        }
        if (!("channel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["channel"] = "";
        }
        if (!("release_notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_notes"] = "";
        }
        if (!("min_supported_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["min_supported_version"] = "";
        }
        if (!("published_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["published_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManifestRelease instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ManifestRelease}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ManifestRelease(/** @type {Partial<ManifestRelease>} */($$parsedSource));
    }
}

export class ManifestUpdate {
    /**
     * Creates a new ManifestUpdate instance.
     * @param {Partial<ManifestUpdate>} [$$source = {}] - The source object to create the ManifestUpdate.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManifestUpdate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ManifestUpdate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ManifestUpdate(/** @type {Partial<ManifestUpdate>} */($$parsedSource));
    }
}

export class PublicManifest {
    /**
     * Creates a new PublicManifest instance.
     * @param {Partial<PublicManifest>} [$$source = {}] - The source object to create the PublicManifest.
     */
    constructor($$source = {}) {
        if (!("schema_version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schema_version"] = 0;
        }
        if (!("generated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["generated_at"] = "";
        }
        if (!("expires_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expires_at"] = "";
        }
        if (!("release" in $$source)) {
            /**
             * @member
             * @type {ManifestRelease}
             */
            this["release"] = (new ManifestRelease());
        }
        if (!("update" in $$source)) {
            /**
             * @member
             * @type {ManifestUpdate}
             */
            this["update"] = (new ManifestUpdate());
        }
        if (!("artifacts" in $$source)) {
            /**
             * @member
             * @type {ManifestArtifacts}
             */
            this["artifacts"] = (new ManifestArtifacts());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicManifest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicManifest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("release" in $$parsedSource) {
            $$parsedSource["release"] = $$createField3_0($$parsedSource["release"]);
        }
        if ("update" in $$parsedSource) {
            $$parsedSource["update"] = $$createField4_0($$parsedSource["update"]);
        }
        if ("artifacts" in $$parsedSource) {
            $$parsedSource["artifacts"] = $$createField5_0($$parsedSource["artifacts"]);
        }
        return new PublicManifest(/** @type {Partial<PublicManifest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = launcheripc$0.ArtifactPayload.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = ManifestRelease.createFrom;
const $$createType3 = ManifestUpdate.createFrom;
const $$createType4 = ManifestArtifacts.createFrom;
