// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ArtifactPayload {
    /**
     * Creates a new ArtifactPayload instance.
     * @param {Partial<ArtifactPayload>} [$$source = {}] - The source object to create the ArtifactPayload.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("package_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["package_type"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_url"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtifactPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArtifactPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArtifactPayload(/** @type {Partial<ArtifactPayload>} */($$parsedSource));
    }
}

export class UpdateAccepted {
    /**
     * Creates a new UpdateAccepted instance.
     * @param {Partial<UpdateAccepted>} [$$source = {}] - The source object to create the UpdateAccepted.
     */
    constructor($$source = {}) {
        if (!("operation_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operation_id"] = "";
        }
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }
        if (!("accepted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["accepted"] = false;
        }
        if (!("duplicate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["duplicate"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateAccepted instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateAccepted}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateAccepted(/** @type {Partial<UpdateAccepted>} */($$parsedSource));
    }
}

export class UpdateApplyRequest {
    /**
     * Creates a new UpdateApplyRequest instance.
     * @param {Partial<UpdateApplyRequest>} [$$source = {}] - The source object to create the UpdateApplyRequest.
     */
    constructor($$source = {}) {
        if (!("schema_version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schema_version"] = 0;
        }
        if (!("request_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["request_id"] = "";
        }
        if (!("force" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["force"] = false;
        }
        if (!("target_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target_version"] = "";
        }
        if (!("manifest" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["manifest"] = null;
        }
        if (!("artifact" in $$source)) {
            /**
             * @member
             * @type {ArtifactPayload}
             */
            this["artifact"] = (new ArtifactPayload());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateApplyRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateApplyRequest}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artifact" in $$parsedSource) {
            $$parsedSource["artifact"] = $$createField5_0($$parsedSource["artifact"]);
        }
        return new UpdateApplyRequest(/** @type {Partial<UpdateApplyRequest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ArtifactPayload.createFrom;
